default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: <%= ENV['DB_HOST'] %>
development:
  <<: *default
  database: shinya_elearning_development
test:
  <<: *default
  database: shinya_elearning_test

  producton:
    adapter: postgresql
    database: shinya_elearning_db
    pool: 5
    timeout: 5000
